version: '3.1'

services:
  teamspeak:
    image: teamspeak:latest
    container_name : teamspeak
    restart: always
    ports:
      - "9987:9987/udp"
      - "10011:10011"
      - "30033:30033"
    environment:
     TS3SERVER_LICENSE: accept
    volumes:
      - "./ts3server:/var/ts3server/"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.teamspeak.rule=Host(`friends.servegame.com`)"
      - "traefik.http.routers.teamspeak.entrypoints=websecure"
      - "traefik.http.routers.teamspeak.tls.certresolver=letsencrypt"
      - "traefik.docker.network=docker"
    depends_on:
      - tsdb
    networks:
      - docker

  tsdb:
    image: mariadb
    container_name : teamspeak_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=teamspeak
      - MYSQL_USER=teamspeak
      - MYSQL_PASSWORD=teamspeak
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - docker

networks:
  docker:
    external: true
