version: '3'

services:
  ocsapplication:
    image: ocsinventory/ocsinventory-docker-image:2.8
    container_name : ocsinventory-server
    restart: always
    volumes:
      - "./perlcomdata:/etc/ocsinventory-server"
      - "./extensionsdata:/usr/share/ocsinventory-reports/ocsreports/"
      - "./varlibdata:/var/lib/ocsinventory-reports"
      - "./httpdconfdata:/etc/httpd/conf.d"
    ports:
      - "801:80"
    environment:
      OCS_DB_SERVER: ocsinventory-db
      OCS_DB_USER: ocsuser
      OCS_DB_PASS: ocspass
      OCS_DB_NAME: ocsweb
      TZ: America/Sao_Paulo
      # See documentation to set up SSL for MySQL
      OCS_SSL_ENABLED: 0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ocs.rule=Host(`ocs.senninfabio.online`)"
      - "traefik.http.routers.ocs.entrypoints=websecure"
      - "traefik.http.routers.ocs.tls.certresolver=letsencrypt"
      - "traefik.http.services.ocs.loadbalancer.server.port=80"
      - "traefik.docker.network=docker"
    links:
      - ocsdb
    networks:       
      - docker
    depends_on:
      - ocsdb    

  ocsdb :
    image : mariadb
    container_name : ocsinventory-db
    restart: always
    volumes :
      - ./sql/:/docker-entrypoint-initdb.d/
      - ./sqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD : rootpass
      MYSQL_USER : ocsuser
      MYSQL_PASSWORD : ocspass
      MYSQL_DATABASE : ocsweb
      TZ: America/Sao_Paulo
    labels:
      - "traefik.enable=false"
    networks:       
      - docker

networks:
  docker:
    external: true
