version: "3.3"
services:
  portainer:
    image: portainer/portainer-ce:2.9.3
    container_name: portainer
    restart: always
    ports:
      - 9000:9000 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data
    network_mode: bridge
