version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: Nginx-Proxy-Manager
    restart: always
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    environment:
        DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    network_mode: bridge  